feat(scan): introduce a client to manage scans via REST API
NeuraLegion/sectester-net pull request #58
Opened 2022-11-23 07:33 UTC by ostridm

closes #44

2022-11-24 09:39 UTC, derevnjuk requested changes
There are a lot of styling and formatting issues, make sure that dotnet tools and husky work as expected. If not, use `dotnet format` manually

2022-11-24 09:39 UTC, derevnjuk commented on src/SecTester.Bus/Extensions/MessageSerializerExtensions.cs
> +  public static HttpContent SerializeJsonContent<T>(this MessageSerializer messageSerializer, T data)
The method name confuses: 
* You serialize data passed by the first argument, but not the content. 
* The content is created by calling this method but not serialized.
* Why does the serializer responsible to create HttpContent?

2022-11-24 09:39 UTC, derevnjuk commented on src/SecTester.Bus/Extensions/MessageSerializerExtensions.cs
> +    return new StringContent(messageSerializer.Serialize(data), Encoding.UTF8, "application/json");
Why don't create `JsonContent` instead?

2022-11-24 09:39 UTC, derevnjuk commented on src/SecTester.Scan/Commands/CreateScan.cs
> +  public CreateScan(HttpContent body, int? ttl = null)
Well, does it mean I can pass `multipart/form-data` with any data to create a scan? It looks like you have to accept DTO to avoid ambiguity

2022-11-24 09:39 UTC, derevnjuk commented on src/SecTester.Scan/Commands/DeleteScan.cs
> +  public DeleteScan(string id, int? ttl = default)
In some place you use the default, but in some null. You have to decide. Also, I don't see any reason to expose TTL for these commands.

2022-11-24 09:39 UTC, derevnjuk commented on src/SecTester.Scan/DefaultScans.cs
> +    requestContent.Add(fileNameContent, "filename");
Since when does the filename is a separate field?
```suggestion
    requestContent.Add(jsonFileContent, "file", fileNameContent);
```

2022-11-24 09:39 UTC, derevnjuk commented on src/SecTester.Scan/DefaultScans.cs
> +    var result =  await SendCommand(new UploadHar(requestContent, options.Discard));
```suggestion
    var result = await SendCommand(new UploadHar(requestContent, options.Discard));
```

2022-11-24 09:39 UTC, derevnjuk commented on src/SecTester.Scan/DefaultScans.cs
> +  }
```suggestion
  public Task<IEnumerable<Issue>> ListIssues(string id)
  {
    return SendCommand(new ListIssues(id));
  }
```

2022-11-24 09:39 UTC, derevnjuk commented on src/SecTester.Scan/DefaultScans.cs
> +    var result = await this._commandDispatcher.Execute(command);
Some unit test frameworks (like xUnit) have their own synchronization context. So, you should use `ConfigureAwait(false)` everywhere. To make this easier, you can add `configure_await_analysis_mode = library` to `.editorconfig`

2022-11-24 09:39 UTC, derevnjuk commented on src/SecTester.Scan/DefaultScans.cs
> +internal class DefaultScans : Scans
It is not clear to me, why commands are public, but this one is internal. It should be the opposite.

2022-11-24 09:39 UTC, derevnjuk commented on src/SecTester.Scan/CI/DefaultCiDiscovery.cs
> +  public CiServer Server { get; } = CiServer.Unknown;
```suggestion
  public CiServer? Server { get; };
```

2022-11-24 09:39 UTC, derevnjuk commented on src/SecTester.Scan/CI/DefaultCiDiscovery.cs
> +  public bool IsCi => Server != CiServer.Unknown;
```suggestion
  public bool IsCi => Server != null;
```

2022-11-24 09:39 UTC, derevnjuk commented on src/SecTester.Scan/CI/DefaultCiDiscovery.cs
> +  public bool IsPr { get; }
Remove unused property

2022-11-24 09:39 UTC, derevnjuk commented on test/SecTester.Scan.Tests/DefaultScansTests.cs
> +    _commandDispatcher.ClearSubstitute();
```suggestion
    _commandDispatcher.ClearSubstitute();
    GC.SuppressFinalize(this);
```

2022-11-24 09:39 UTC, derevnjuk commented on test/SecTester.Scan.Tests/Extensions/TaskExtensions.cs
> +  public static TResult? GetSync<T, TResult>(this T? t, Func<T, Task<TResult>> func)
Please follow conventions

```suggestion
  public static TResult? ContinueWithSycn<T, TResult>(this T? t, Func<T, Task<TResult>> continuationFunction)
```

2022-11-24 09:39 UTC, derevnjuk commented on test/SecTester.Scan.Tests/Extensions/TaskExtensions.cs
> +public static class TaskExtensions
This extension must be internal

2022-11-24 09:39 UTC, derevnjuk commented on test/SecTester.Scan.Tests/DefaultScansTests.cs
> +    Func<HttpContent?, bool> uploadHarContentMatcher = httpContent =>
Well, the expectation is too complex. You just need to make sure that one of an item of `MultipartFormDataContent` contains a field with a `jsonFileContent`

2022-11-24 09:39 UTC, derevnjuk commented on test/SecTester.Scan.Tests/DefaultScansTests.cs
> +        x.Params.Any(y => y.Key == "discard" && y.Value == "true")));
It is not clear why you test `UploadHar` here. How does it relate to Scans? You just need to make sure that the command dispatcher receives a proper instance of `UploadHar`

2022-11-24 09:39 UTC, derevnjuk commented on test/SecTester.Scan.Tests/DefaultScansTests.cs
> +          x.Params == null || x.Params.All(y => y.Key != "discard"))));
ditto

2022-11-24 09:39 UTC, derevnjuk commented on test/SecTester.Scan.Tests/DefaultScansTests.cs
> +        x.Url.EndsWith($"/api/v1/scans/{ScanId}") && x.Method == HttpMethod.Get && x.ExpectReply));
ditto

2022-11-24 09:39 UTC, derevnjuk commented on test/SecTester.Scan.Tests/DefaultScansTests.cs
> +      .Execute(Arg.Is<DeleteScan>(x => x.Url.EndsWith($"/api/v1/scans/{ScanId}/delete") && x.Method == HttpMethod.Get));
ditto

2022-11-24 09:39 UTC, derevnjuk commented on test/SecTester.Scan.Tests/DefaultScansTests.cs
> +      .Execute(Arg.Is<StopScan>(x => x.Url.EndsWith($"/api/v1/scans/{ScanId}/stop") && x.Method == HttpMethod.Get));
ditto

2022-11-24 09:39 UTC, derevnjuk commented on test/SecTester.Scan.Tests/DefaultScansTests.cs
> +        x.Url.EndsWith($"/api/v1/scans/{ScanId}/issues") && x.Method == HttpMethod.Get && x.ExpectReply));
ditto

2022-11-24 09:39 UTC, derevnjuk commented on test/SecTester.Scan.Tests/DefaultScansTests.cs
> +  public async Task UploadHar_WhenResultIsNull_ThrowError()
```suggestion
  public async Task UploadHar_ResultIsNull_ThrowError()
```

2022-11-24 09:39 UTC, derevnjuk commented on test/SecTester.Scan.Tests/DefaultScansTests.cs
> +  public async Task GetScan_WhenResultIsNull_ThrowError()
```suggestion
  public async Task GetScan_ResultIsNull_ThrowError()
```

2022-11-24 09:39 UTC, derevnjuk commented on test/SecTester.Scan.Tests/DefaultScansTests.cs
> +  public async Task ListIssues_WhenResultIsNull_ThrowError()
```suggestion
  public async Task ListIssues_ResultIsNull_ThrowError()
```

2022-11-24 09:39 UTC, derevnjuk commented on test/SecTester.Scan.Tests/DefaultScansTests.cs
> +  public async Task ListIssues_ReturnAListOfIssues()
```suggestion
  public async Task ListIssues_ReturnListOfIssues()
```

2022-11-24 09:39 UTC, derevnjuk commented on test/SecTester.Scan.Tests/DefaultScansTests.cs
> +  public async Task CreateScan_WhenResultIsNull_ThrowError()
```suggestion
  public async Task CreateScan_ResultIsNull_ThrowError()
```

2022-11-24 09:39 UTC, derevnjuk commented on test/SecTester.Scan.Tests/DefaultScansTests.cs
> +                                       x.ExpectReply &&
ditto

2022-11-24 09:39 UTC, derevnjuk commented on test/SecTester.Scan.Tests/DefaultScansTests.cs
> +      .Returns(Task.FromResult<Identifiable<string>?>(new Identifiable<string>("id")));
The test data must be as close as possible to real

2022-11-24 09:39 UTC, derevnjuk commented on test/SecTester.Scan.Tests/DefaultScansTests.cs
> +    FileId = "fileId",
ditto

2022-11-24 09:39 UTC, derevnjuk commented on test/SecTester.Scan.Tests/DefaultScansTests.cs
> +    ProjectId = "projectId",
ditto

2022-11-24 09:39 UTC, derevnjuk commented on test/SecTester.Scan.Tests/DefaultScansTests.cs
> +    Repeaters = new[] { "repeater1" },
ditto

2022-11-24 09:39 UTC, derevnjuk commented on test/SecTester.Bus.Tests/Extensions/MessageSerializerExtensionsTests.cs
> +    // arrange
```suggestion
  {
    // arrange
```

2022-11-24 09:54 UTC, ostridm commented on src/SecTester.Bus/Extensions/MessageSerializerExtensions.cs
> +    return new StringContent(messageSerializer.Serialize(data), Encoding.UTF8, "application/json");
`JsonContent` is missing when the target is `netstadard`. It appears for `.net 5` and above.

2022-11-25 11:46 UTC, derevnjuk requested changes

2022-11-25 11:46 UTC, derevnjuk commented on src/SecTester.Scan/Commands/CreateScan.cs
> +    var payload = new
I don't like that you delegate creating a DTO to the command.

2022-11-25 11:46 UTC, derevnjuk commented on test/SecTester.Scan.Tests/Commands/DeleteScanTests.cs
> +public class DeleteScanTests : ScanFixture
We have already discussed, the constructor must be tested only in the case of presence logic.

2022-11-25 11:46 UTC, derevnjuk commented on test/SecTester.Scan.Tests/Commands/GetScanTests.cs
> +public class GetScanTests : ScanFixture
ditto

2022-11-25 11:46 UTC, derevnjuk commented on test/SecTester.Scan.Tests/Commands/ListIssuesTests.cs
> +public class ListIssuesTests : ScanFixture
ditto

2022-11-25 11:46 UTC, derevnjuk commented on test/SecTester.Scan.Tests/Commands/StopScanTests.cs
> +public class StopScanTests : ScanFixture
ditto

2022-11-25 11:46 UTC, derevnjuk commented on src/SecTester.Scan/Content/DefaultHttpContentFactory.cs
> +  public virtual HttpContent CreateHarContent(UploadHarOptions options)
Well, I don't see any reason to introduce a method that will be used only once in the particular case

2022-11-25 11:46 UTC, derevnjuk commented on src/SecTester.Scan/Content/DefaultHttpContentFactory.cs
> +public class DefaultHttpContentFactory : HttpContentFactory
Actually, I don't see any reason to have such a class. Let's discuss this on our call

2022-11-25 11:46 UTC, derevnjuk commented on src/SecTester.Scan/Commands/CreateScan.cs
> +    : base("/api/v1/scans", HttpMethod.Post)
The commands should not depend on any kind of service, it makes them unusable. According to the concept, they must be immutable simple POJO/DTO

2022-11-25 11:46 UTC, derevnjuk commented on test/SecTester.Scan.Tests/Commands/UploadHarTests.cs
> +    command.Params.Should().BeNull();
You shiould use a partial matcher instead

```csharp
command.Should(). BeEquivalentTo(new {})
```

2022-11-25 11:46 UTC, derevnjuk commented on test/SecTester.Scan.Tests/Commands/StopScanTests.cs
> +    command.ExpectReply.Should().BeFalse();
ditto

2022-11-25 11:46 UTC, derevnjuk commented on test/SecTester.Scan.Tests/Commands/ListIssuesTests.cs
> +    command.ExpectReply.Should().BeTrue();
ditto

2022-11-25 11:46 UTC, derevnjuk commented on test/SecTester.Scan.Tests/Commands/GetScanTests.cs
> +    command.ExpectReply.Should().BeTrue();
ditto

2022-11-25 11:46 UTC, derevnjuk commented on test/SecTester.Scan.Tests/Commands/DeleteScanTests.cs
> +    command.ExpectReply.Should().BeFalse();
ditto

2022-11-25 11:46 UTC, derevnjuk commented on test/SecTester.Scan.Tests/Commands/CreateScanTests.cs
> +    command.ExpectReply.Should().BeTrue();
ditto

2022-11-28 09:44 UTC, derevnjuk requested changes

2022-11-28 09:44 UTC, derevnjuk commented on test/SecTester.Scan.Tests/DefaultScansTests.cs
> +    await _sut.DeleteScan(ScanId).ConfigureAwait(false);
Erm, why do you do this in tests?

2022-11-28 09:44 UTC, derevnjuk commented on test/SecTester.Scan.Tests/Models/UploadHarOptionsTests.cs
> +using SecTester.Scan.Target.Har;
We are using global using

2022-11-28 09:44 UTC, derevnjuk commented on test/SecTester.Scan.Tests/Target/TargetTests.cs
> +using SecTester.Scan.Target.Har;
ditto

2022-11-28 09:44 UTC, derevnjuk commented on test/SecTester.Scan.Tests/Fixtures/ScanFixture.cs
> +using SecTester.Scan.Models;
ditto

2022-11-28 09:44 UTC, derevnjuk commented on test/SecTester.Scan.Tests/DefaultScansTests.cs
> +using Request = SecTester.Scan.Models.Request;
ditto

2022-11-28 09:44 UTC, derevnjuk commented on test/SecTester.Scan.Tests/Commands/CreateScanTests.cs
> +using SecTester.Scan.Tests.Fixtures;
ditto

2022-11-28 09:44 UTC, derevnjuk commented on test/SecTester.Scan.Tests/CI/DefaultCiDiscoveryTests.cs
> +using SecTester.Scan.CI;
ditto

2022-11-28 11:49 UTC, derevnjuk commented
@ostridm make sure that husky is working in your case, otherwise, manually format files before pushing. Make sure that you utilize LF instead of CRLF https://github.com/NeuraLegion/sectester-net/pull/58/commits/67cb3da2a34aa9c09ed28bcaa5a7186451ef2113

2022-11-28 11:53 UTC, derevnjuk approved these changes

2022-11-28 11:53 UTC, merged