feat(scan): provide a default scan factory
NeuraLegion/sectester-net pull request #76
Opened 2022-11-29 15:49 UTC by ostridm

closes #68

2022-12-02 16:31 UTC, derevnjuk requested changes
BTW comment in Issue and comment in Har are not the same thing

2022-12-02 16:31 UTC, derevnjuk commented on src/SecTester.Scan/Target/Har/Response.cs
> +public record Response(int Status, string StatusText, string HttpVersion, IEnumerable<Cookie> Cookies,
`Response` should extend `Message`. It is pointless to add all the fields into constructors, we have already discussed this. The fields like `Cookies` or `Headers` should have a default value

2022-12-02 16:31 UTC, derevnjuk commented on src/SecTester.Scan/Target/Har/Entry.cs
> +public record Entry(DateTime StartedDateTime, int Time, Timings Timings, Cache Cache, Request Request,
ditto

2022-12-02 16:31 UTC, derevnjuk commented on src/SecTester.Scan/Target/Har/Log.cs
> +public record Log(Tool Creator, IEnumerable<Entry> Entries, string Version = "1.2")
ditto

2022-12-02 16:31 UTC, derevnjuk commented on src/SecTester.Scan/Target/Har/Timings.cs
> +public record Timings(int Wait, int Receive)
ditto

2022-12-02 16:31 UTC, derevnjuk commented on src/SecTester.Scan/Target/Har/Timings.cs
> +  public int? Send { get; init; }
The `Send` is required like `Wait` or `Receive`, but all of them have default values

2022-12-02 16:31 UTC, derevnjuk commented on src/SecTester.Scan/Target/Har/Timings.cs
> +  public static readonly Timings Default = new(0, 0) { Send = 0 };
It is pointless to have `Default` static field, see comment above

2022-12-02 16:31 UTC, derevnjuk commented on test/SecTester.Scan.Tests/Extensions/HttpContentExtensions.cs
> +internal static class HttpContentExtensions
I didn't get it, why do all your PR contain the same changes? How you are going to resolve conflicts? Why do these changes relate to this PR?

2022-12-02 16:31 UTC, derevnjuk commented on src/SecTester.Scan/ScanSettings.cs
> +    IEnumerable<AttackParamLocation>? attackParamLocations)
According to the interface, almost all parameters are optional, why do you need to introduce this huge constructor? The constructor should contain only the required parameters, everything else should be initialized using object initializers

2022-12-02 16:31 UTC, derevnjuk commented on src/SecTester.Scan/ScanSettings.cs
> +    .Cast<AttackParamLocation>();
You should use `Enum.IsDefined(typeof(AttackParamLocation), value)`

2022-12-02 16:31 UTC, derevnjuk commented on src/SecTester.Scan/ScanSettings.cs
> +  private static void AssertEnum<T>(IEnumerable<T>? value, IEnumerable<T> whiteList,
Such methods should never be an instance or class member. Also, I don't see any reason to have so a weak method at all: unclear signature, irrelevant name, etc

2022-12-02 16:31 UTC, derevnjuk commented on src/SecTester.Scan/ScanSettings.cs
> +  private IEnumerable<TestType> _tests = null!;
Why do you initialize them with null?

2022-12-02 16:31 UTC, derevnjuk commented on src/SecTester.Scan/ScanSettings.cs
> +          value!.Length is < MinNameLength or > MaxNameLength)
`string.IsNullOrWhiteSpace(value)` and `value!.Length is < MinNameLength` do the same job

2022-12-02 16:31 UTC, derevnjuk commented on src/SecTester.Scan/ScanSettings.cs
> +    var name = $"{target.Method ?? HttpMethod.Get} {uri.Host}";
ditto

2022-12-02 16:31 UTC, derevnjuk commented on src/SecTester.Scan/ScanSettings.cs
> +  private static string CreateDefaultName(TargetOptions target)
`TargetOptions` shouldn't be used to retrieve `Url` (URL must be normalized). It is already done in `Target`

2022-12-02 16:31 UTC, derevnjuk commented on src/SecTester.Scan/ScanSettings.cs
> +    var name = $"{target.Method ?? HttpMethod.Get} {uri.Host}";
ditto

2022-12-02 16:31 UTC, derevnjuk commented on src/SecTester.Scan/ScanSettings.cs
> +  private static string CreateDefaultName(TargetOptions target)
`TargetOptions` shouldn't be used to retrieve `Url` (URL must be normalized). It is already done in `Target`

2022-12-02 16:31 UTC, derevnjuk commented on src/SecTester.Scan/ScanSettings.cs
> +  private static string CreateDefaultName(TargetOptions target)
`TargetOptions` shouldn't be used to retrieve `Url` (URL must be normalized). It is already done in `Target`

2022-12-02 16:31 UTC, derevnjuk commented on src/SecTester.Scan/ScanSettings.cs
> +    return name.Length <= MaxNameLength ? name : name.Substring(0, MaxNameLength);
The last symbol must be replace with `…` once name is truncated

2022-12-02 16:31 UTC, derevnjuk commented on src/SecTester.Scan/ScanSettings.cs
> +    set
Each accessible field must be init only https://github.com/NeuraLegion/sectester-net/pull/47#discussion_r1023926331

2022-12-02 16:31 UTC, derevnjuk commented on src/SecTester.Scan/ScanSettings.cs
> +  private const int DefaultPoolSize = 10;
Why do you introduce these static fields? Why don't assign default values directly to the accessible fields?

2022-12-02 16:31 UTC, derevnjuk commented on src/SecTester.Scan/ScanSettings.cs
> +  };
ditto

2022-12-02 16:31 UTC, derevnjuk commented on src/SecTester.Scan/ScanSettings.cs
> +    get { return _name; }
Use expression body where it is possible
```suggestion
    get => _name;
```

2022-12-02 16:31 UTC, derevnjuk commented on src/SecTester.Scan/Scan.cs
> +    _logger = logger ?? throw new ArgumentNullException(nameof(logger));
You don't use the logger, why did you add it here?

2022-12-02 16:31 UTC, derevnjuk commented on src/SecTester.Scan/Target/Har/Response.cs
> +    new List<Header>(), "", -1, -1, Content.Default);
This is the default value for `ScanFactory`, but it has nothing in common with the default value for HAR spec in general

2022-12-02 16:31 UTC, derevnjuk commented on src/SecTester.Scan/DefaultScanFactory.cs
> +  private const int HarDefaultNameMaxHostLength = 200;
Har default name max host length? What? 
```suggestion
  private const int MaxSlugLength = 200;
```

2022-12-02 16:31 UTC, derevnjuk commented on src/SecTester.Scan/DefaultScanFactory.cs
> +  private async Task<ScanConfig> BuildScanConfig(ScanSettingsOptions settingsOptions)
```suggestion
  private async Task<ScanConfig> BuildScanConfig(ScanSettings settings)
```

2022-12-02 16:31 UTC, derevnjuk commented on src/SecTester.Scan/DefaultScanFactory.cs
> +    return $"{host.TrimEnd('-')}-{Guid.NewGuid().ToString()}.har";
```suggestion
    return $"{host.TrimEnd('-')}-{Guid.NewGuid()}.har";
```

2022-12-05 08:15 UTC, ostridm commented on src/SecTester.Scan/Target/Har/Timings.cs
> +  public int? Send { get; init; }
`Send` is optional in `har-sdk`
https://github.com/NeuraLegion/har-sdk/blob/10baaf123200ad80d0262778c4069fe82d28727d/packages/core/src/types/har.ts#L818

2022-12-05 10:17 UTC, derevnjuk commented on src/SecTester.Scan/Target/Har/Timings.cs
> +  public int? Send { get; init; }
You can refer to whatever you want, but this has nothing in common with the spec http://www.softwareishard.com/blog/har-12-spec/

2022-12-06 07:19 UTC, derevnjuk requested changes
Please describe how to use the project in README

2022-12-06 07:19 UTC, derevnjuk commented on test/SecTester.Scan.Tests/Mocks/MockLogger.cs
> +internal abstract class MockLogger : ILogger
There are a lot of duplicates from your previous PR. How do you want me to review them? https://github.com/NeuraLegion/sectester-net/pull/76#discussion_r1038232222

2022-12-06 08:16 UTC, ostridm commented on test/SecTester.Scan.Tests/Mocks/MockLogger.cs
> +internal abstract class MockLogger : ILogger
@derevnjuk Nope, I am going to rebase this PR after #59 is merged. Convert it to draft for a while.

2022-12-06 11:43 UTC, derevnjuk requested changes

2022-12-06 11:43 UTC, derevnjuk commented on test/SecTester.Scan.Tests/Commands/UploadHarTests.cs
> +      new Tool("Configuration_Name", "Configuration_Version"))
Avoid using any cryptic and weird test data
```suggestion
      new Tool("name", "v1.1.1"))
```

2022-12-06 11:43 UTC, derevnjuk commented on test/SecTester.Core.Tests/Utils/StringUtilsTests.cs
> +    new object[] { "aa", "aa", 3 }
What is difference between this `"a", "a", 1` and these sets? Remove similar test cases. Instead of inventing bicycle, just reuse described in sectester-js

2022-12-06 11:43 UTC, derevnjuk commented on test/SecTester.Core.Tests/Utils/StringUtilsTests.cs
> +  public void Truncate_SatisfyConversion(string input, string expected, int length)
`Length` is also input) The argument name are confusing

2022-12-06 11:43 UTC, derevnjuk commented on src/SecTester.Core/Utils/StringUtils.cs
> +  public static string? Truncate(this string? value, int n)
It is not clear why you accept nullable input, this is weak design

2022-12-06 11:43 UTC, derevnjuk commented on test/SecTester.Core.Tests/Utils/StringUtilsTests.cs
> +  public static readonly IEnumerable<object[]> TruncateMapping = new List<object[]>
Mapping?

2022-12-06 11:43 UTC, derevnjuk commented on src/SecTester.Core/Utils/StringUtils.cs
> +      : $"{value.Substring(0, n)}…";
Invert condition to avoid redundant checks and uncertainty

2022-12-06 11:43 UTC, derevnjuk commented on src/SecTester.Core/Utils/StringUtils.cs
> +      : $"{value.Substring(0, n)}…";
Your implementation work is unexpected, you violate the postcondition.

2022-12-06 11:43 UTC, derevnjuk commented on src/SecTester.Scan/README.md
> +## Usage
There are ton of formatting issues and oddities in both code snippets and text.

2022-12-06 11:43 UTC, derevnjuk commented on test/SecTester.Scan.Tests/ScanSettingsTests.cs
> +  public void PublicConstructor_CreatesInstanceWithDefaultOptions()
```suggestion
  public void ScanSettings_CreatesInstanceWithDefaultOptions()
```

2022-12-06 11:43 UTC, derevnjuk commented on test/SecTester.Scan.Tests/ScanSettingsTests.cs
> +  public void InternalConstructor_CreatesInstance()
```suggestion
  public void ScanSettings_ScanSettingsOptionsPassed_CreatesInstance()
```

2022-12-06 11:43 UTC, derevnjuk commented on test/SecTester.Scan.Tests/ScanSettingsTests.cs
> +    _scanSettingsOptions.ClearSubstitute();
```suggestion
    _scanSettingsOptions.ClearSubstitute();
    GC.SuppressFinalize(this);
```

2022-12-06 11:43 UTC, derevnjuk commented on test/SecTester.Scan.Tests/ScanSettingsTests.cs
> +    _scanSettingsOptions.AttackParamLocations.Returns(new List<AttackParamLocation> { AttackParamLocation.Query });
It is bad practice to use mock or stubs for test data. Moreover, this is pointless

2022-12-06 11:43 UTC, derevnjuk commented on test/SecTester.Scan.Tests/ScanSettingsTests.cs
> +    yield return new object[]
Why do you use custom iterator instead of a list like in other places??

2022-12-06 11:43 UTC, derevnjuk commented on test/SecTester.Scan.Tests/ScanSettingsTests.cs
> +  public void Setter_GivenInvalidInput_ThrowError(string expectedMessage,
```suggestion
  public void Setter_GivenInvalidInput_ThrowsError(string expected,
```

2022-12-06 11:43 UTC, derevnjuk commented on test/SecTester.Scan.Tests/ScanSettingsTests.cs
> +    Func<ScanSettings, ScanSettings> action)
This is a mutator or test data factory, but exactly not action.

2022-12-06 11:43 UTC, derevnjuk commented on test/SecTester.Scan.Tests/ScanSettingsTests.cs
> +  public void InternalConstructor_CreatesInstanceWithUniqueTests()
ditto (you want to say that this case is not applicable for other constructors?)

2022-12-06 11:43 UTC, derevnjuk commented on test/SecTester.Scan.Tests/ScanSettingsTests.cs
> +  public void InternalConstructor_CreatesInstanceWithUniqueAttackParamLocations()
ditto

2022-12-06 11:43 UTC, derevnjuk commented on test/SecTester.Scan.Tests/ScanSettingsTests.cs
> +    result.Should().BeEquivalentTo(new { Name = $"GET {new string('a', 195)}…" });
Should we tune this value each time when something is changed?

2022-12-06 11:43 UTC, derevnjuk commented on test/SecTester.Scan.Tests/ScanSettingsTests.cs
> +  public void InternalConstructor_NameIsNull_CreatesInstanceTruncatedHost()
What about the case with non-default name that is greater than 200 characters?

2022-12-06 11:43 UTC, derevnjuk commented on test/SecTester.Scan.Tests/ScanSettingsTests.cs
> +    _scanSettingsOptions.Name.ReturnsForAnyArgs(_ => null);
Why do you use `ReturnsForAnyArgs` if this is a property that definitely does not accept any arguments?

2022-12-06 11:43 UTC, derevnjuk commented on test/SecTester.Scan.Tests/Models/UploadHarOptionsTests.cs
> +      new Tool("Configuration_Name", "Configuration_Version")
ditto

2022-12-06 11:43 UTC, derevnjuk commented on test/SecTester.Scan.Tests/Models/UploadHarOptionsTests.cs
> +  private static readonly Har Har = new(
Avoid using static test data

2022-12-06 11:43 UTC, derevnjuk commented on test/SecTester.Scan.Tests/DefaultScansTests.cs
> +      new Tool("Configuration_Name", "Configuration_Version")
ditto

2022-12-06 11:43 UTC, derevnjuk commented on test/SecTester.Scan.Tests/DefaultScansTests.cs
> +  private static readonly Har Har = new(
ditto

2022-12-06 11:43 UTC, derevnjuk commented on test/SecTester.Scan.Tests/DefaultScanFactoryTests.cs
> +  private readonly ScanSettingsOptions _options = Substitute.For<ScanSettingsOptions>();
ditto

2022-12-06 11:43 UTC, derevnjuk commented on test/SecTester.Scan.Tests/DefaultScanFactoryTests.cs
> +    _options.AttackParamLocations.ReturnsForAnyArgs(null as IEnumerable<AttackParamLocation>);
Why is it necessary? That has nothing in common with this particular test case

2022-12-06 11:43 UTC, derevnjuk commented on test/SecTester.Scan.Tests/DefaultScanFactoryTests.cs
> +    _options.AttackParamLocations.ReturnsForAnyArgs(null as IEnumerable<AttackParamLocation>);
ditto

2022-12-06 11:43 UTC, derevnjuk commented on test/SecTester.Scan.Tests/DefaultScanFactoryTests.cs
> +    _options.AttackParamLocations.ReturnsForAnyArgs(null as IEnumerable<AttackParamLocation>);
ditto

2022-12-06 11:43 UTC, derevnjuk commented on src/SecTester.Scan/Target/Har/Response.cs
> +  public string RedirectUrl { get; init; } = "";
No such default values according to spec or even sense

2022-12-06 11:43 UTC, derevnjuk commented on src/SecTester.Scan/Target/Har/Entry.cs
> +  public int Time { get; init; }
```suggestion
  public int Time { get; init; } = 0
```

2022-12-06 11:43 UTC, derevnjuk commented on src/SecTester.Scan/Target/Har/Entry.cs
> +  public Response? Response { get; init; }
All of them are mandatory fields according to spec

2022-12-06 11:43 UTC, derevnjuk commented on src/SecTester.Scan/Target/Har/Content.cs
> +public record Content(int Size = -1, string MimeType = "text/plain");
ditto

2022-12-06 11:43 UTC, derevnjuk commented on src/SecTester.Scan/ScanSettings.cs
> +    Name = CreateDefaultName(_target!);
```suggestion
    Name = CreateDefaultName(_target);
```

2022-12-06 11:43 UTC, derevnjuk commented on src/SecTester.Scan/ScanSettings.cs
> +    Name = string.IsNullOrWhiteSpace(scanSettingsOptions.Name) ? CreateDefaultName(_target!) : scanSettingsOptions.Name;
```suggestion
    Name = string.IsNullOrWhiteSpace(scanSettingsOptions.Name) ? CreateDefaultName(_target) : scanSettingsOptions.Name;
```

2022-12-06 11:43 UTC, derevnjuk commented on src/SecTester.Scan/ScanSettings.cs
> +      if (value is null or < 1 or > 50)
Why did you remove a dedicated fields/properties for magic numbers?

2022-12-06 11:43 UTC, derevnjuk commented on src/SecTester.Scan/ScanSettings.cs
> +      if (value is null || (value < TimeSpan.FromSeconds(1) || value > TimeSpan.FromSeconds(120)))
ditto

2022-12-06 11:43 UTC, derevnjuk commented on src/SecTester.Scan/ScanSettings.cs
> +      if (value is null || value < TimeSpan.FromSeconds(100))
ditto

2022-12-06 11:43 UTC, derevnjuk commented on src/SecTester.Scan/DefaultScanFactory.cs
> +      Timings = new Timings { Send = 0, Receive = 0, Wait = 0 },
```suggestion
      Timings = new Timings(),
```

2022-12-06 11:43 UTC, derevnjuk commented on src/SecTester.Scan/DefaultScanFactory.cs
> +        Headers = new List<Header>()
All of them have default values

```suggestion
        RedirectUrl = ""
```

2022-12-06 11:43 UTC, derevnjuk commented on src/SecTester.Scan/DefaultScanFactory.cs
> +      Time = 0,
ditto

2022-12-08 18:00 UTC, derevnjuk approved these changes

2022-12-08 18:08 UTC, merged